[workspace]
members = [
    "chat-core",
    "chat-macros",
    "chat-server",
    "chat-client"
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
# debug = true

# Optimizes dependencies
[profile.dev.package."*"]
opt-level = 3
debug = false
